apiVersion: apps/v1
kind: Deployment
metadata:
  name: cm-demo-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cm-demo
  template:
    metadata:
      labels:
        app: cm-demo
    spec:
      containers:
        - name: cm-demo
          image: satishkarengula/demo-pyapp:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          